---
title: "homework_03"
author: "Sanjana Sujeet"
date: "2025-05-28"
output: html_document
---

```{r setup, message=FALSE}
library(tidyverse)
library(janitor)
library(here)
library(gt)
```


**GitHub Repository:** [https://github.com/sanjanasujeet/ENVS-193DS_workshop-07](https://github.com/sanjanasujeet/ENVS-193DS_workshop-07)

## a. Data Summarizing

My data tracked hours I read, pages I read, and social hours per day as my response variables and stress level as my predictor variable. I don't think I will analyze all these variables but the main thing that I want to look at is how stress levels affect my reading.  

I will compare the number of hours I read per day to my quantified daily stress level, which I calculated based on the number of upcoming assignments and tests, as well as my perceived stress. I also want to calculate my reading pace by dividing pages read by minutes reading and compare this to my stress level to see if stress influences the pace that I read.

To summarize my data, I could calculate the mean number of hours I read per day across different stress levels ( low, medium, high stress). I could also compare the average reading pace between these groups to see if stress impacts not just how much I read, but how fast I read. Comparing means within stress levels is informative because it is a simple way to see if there is a difference between how different stress levels affect me. I may read less efficiently when I feel overwhelmed, or I may read more when trying to avoid stress through a calming activity.





